version: '3'
services: 
  app:
    container_name: vaccination-status-project
    restart: always
    build: .
    ports: 
      - '3000:3000'
    links: 
      - db
  db:
    container_name: postgres
    image: postgres
    ports: 
      - '5432:5432'